|BUILD CONFIGURATION| [Pandora] * The new build system is working correctly with the Pandora
|SOURCE|
[Arithmetic::Matrix3x3]
* Fixed the friend Vector3 issue, declared as a class
[Arithmetic::Matrix4x4]
* Transform returns a value instead of a reference
[System::DataTypes_PandoraLinux]
* Added header file for Linux version of the Pandora build
[System::Trace]
* ZED_SINT32 is returned instead of a now-unavailable ZED_INT32

diff --git a/Source/Pandora/MakefileCommon b/Source/Pandora/MakefileCommon
--- a/Source/Pandora/MakefileCommon
+++ b/Source/Pandora/MakefileCommon
@@ -1,24 +1,41 @@
-TARGET	:= libZED$(ZEDTARGET).a
+ifndef $(TARGET)
+TARGET = libZED$(notdir $(CURDIR)).$(EXT)
+endif
 
-COMMONDIR ?= ../../..
+ifndef $(OBJSDIR)
+OBJSDIR = $(TOPDIR)/Obj/$(PLATFORM)/$(ARCH)/$(BITSIZE)/$(notdir $(CURDIR))/GCC/$(GCCVER)/$(BUILD)
+endif
 
-TARGETDIR = $(COMMONDIR)/Lib/$(PLATFORM)
-OBJDIR = $(COMMONDIR)/Obj/$(PLATFORM)/$(ZEDTARGET)/$(BUILD)
-SOURCEDIR = Source
-HEADERDIR = Headers
+ifndef TARGETDIR
+export TARGETDIR = $(TOPDIR)/Lib/$(PLATFORM)/$(ARCH)/$(BITSIZE)
+export SOURCEDIR = Source
+export HEADERDIR = Headers
+endif
 
-COPYHEADERS ?= True
+OUTFILE = $(TARGETDIR)/$(TARGET)
+SHARED ?= False
+NOLIB ?= False
+COPYFILES ?= True
+#SOURCEDIR = Source
+#HEADERDIR = Headers
+
+#COPYHEADERS ?= True
 
 # Get the machine type for cross compilation
 TOOL_PREFIX		= pandora-
 
-COMMONINCDIR = ../../Common/Headers
+#COMMONINCDIR = ../../Common/Headers
 
-BUILD_PLATFORM	= PANDORA
-PLATFORM		= Pandora
+BUILD_PLATFORM	= PANDORA_LINUX
+PLATFORM		= Pandora_Linux
+BUILD_ARCH		= ARM
+ARCH			= arm
+BITSIZE			= 32
+BUILD_TYPE		= debug
 
 CPP = $(TOOL_PREFIX)g++
 AR	= $(TOOL_PREFIX)ar
+GCCVER = $(shell $(CPP) -dumpversion)
 
 # Set the library path
 ifeq ($(strip $(GCCDIR)),)
@@ -28,22 +45,39 @@ SYSL = /usr/lib
 endif
 
 CPPFLAGS =		-c -DZED_BUILD_$(ZED_BUILD) -DZED_PLATFORM_$(BUILD_PLATFORM) \
-				-DZED_PLATFORM_$(BUILD_PLATFORM)_$(ARCH) \
-				-DZED_PLATFORM_$(BUILD_PLATFORM)_$(ARCH)_$(BITSIZE) \
-				-DZED_BITSIZE_$(BITSIZE) -DZED_ARCH_$(ARCH) -DSUPPORT_X11 
+				-DZED_PLATFORM_$(BUILD_PLATFORM)_$(BUILD_ARCH) \
+				-DZED_PLATFORM_$(BUILD_PLATFORM)_$(BUILD_ARCH)_$(BITSIZE) \
+				-DZED_BITSIZE_$(BITSIZE) -DZED_ARCH_$(ARCH) -DSUPPORT_X11 \
+				-I$(TOPSRC)/Common/Headers -IHeaders
 CPPFLAGS_EXT =	-ffriend-injection -std=c++0x -mcpu=cortex-a8 \
 				-Wa,-mcpu=cortex-a8 -mfpu=neon -Wa,-mfpu=neon \
 				-mfloat-abi=softfp
 SYSIPATH =		-idirafter $(PNDSDK)/usr/include
 
+ifneq ($(SHARED),False)
+	EXT			:= so
+	LINKFLAGS	+= -shared
+	CPPFLAGS	+= -fPIC
+debug:		LINKFLAGS += -Wl,-soname,lib$(notdir $(CURDIR))D.so.1
+release:	LINKFLAGS += -Wl,-soname,lib$(notdir $(CURDIR)).so.1
+profile:	LINKFLAGS += -Wl,-soname,lib$(notdir $(CURDIR))P.so.1
+else
+	EXT	:= a
+endif
+
 ##### Debug Target #####
 debug: BUILD = Debug
+debug: BUILD_TYPE = debug
 debug: ZED_BUILD = DEBUG
-debug: TARGET := libZED$(ZEDTARGET)D.a
+debug: TARGET := libZED$(notdir $(CURDIR))D.$(EXT)
 debug: CPPFLAGS += -g -ggdb -Wall -D_DEBUG $(CPPFLAGS_EXT)
+ifneq ($(NOLIB), True)
 debug: $(TARGET)
-ifeq ($(COPYHEADERS),True)
-debug: copy
+else
+debug: $(TARGET)
+endif
+ifeq ($(COPYFILES), True)
+debug: copyfiles
 endif
 
 ##### Release Target #####
@@ -64,49 +98,202 @@ profile: copy
 endif
 
 ##### Build the object files while not in the object directory
-ifneq ($(OBJDIR), $(CURDIR))
+ifneq ($(OBJSDIR), $(CURDIR))
+
+
+ifeq ($(TOPDIR)/Source/Pandora/$(notdir $(CURDIR)),$(CURDIR))
 
 $(TARGETDIR):
+	@printf "Creating directory: $(TARGETDIR) ... "
 	@mkdir -p $(TARGETDIR)
+	@printf "[OK]\n"
+
 $(OBJSDIR):
+	@printf "Creating dirctory: $(OBJSDIR) ... "
 	@mkdir -p $(OBJSDIR)
+	@printf "[OK]\n"
 
 CPPFILES	:= $(foreach dir,$(SOURCEDIR),$(notdir $(wildcard $(dir)/*.cpp)))
 
-OBJS = $(CPPFILES:.cpp=.o)
+export VPATH := $(foreach dir,$(SOURCEDIR),$(CURDIR)/$(dir))
+export OBJS = $(CPPFILES:.cpp=.o)
 
-$(TARGET): $(OBJS) $(TARGETDIR)
+$(TARGET): $(TARGETDIR) $(OBJSDIR)
+	@mkdir -p $(TARGETDIR)
+	@mkdir -p $(OBJSDIR)
+	@printf "Compiling platform-specific object files for $(TARGET)\n"
+	@/usr/bin/time -f "%E" -o $(OBJSDIR)/compiletime \
+	$(MAKE) --no-print-directory -C $(OBJSDIR) \
+	-f $(TOPSRC)/Pandora/MakefileCommon TARGET=$(TARGET) OBJSDIR=$(OBJSDIR) \
+	LOCALINCDIR=$(CURDIR)/Headers ZEDINCDIR=$(ZEDINCDIR) \
+	COPYFILES=False $(BUILD_TYPE)
 	@printf "%s" "------------------------------------------------------------"
 	@printf "%s\n" "-------------------"
-	@echo Making $(TARGET)
+	@printf "Compile Time: "
+	@cat $(OBJSDIR)/compiletime
 	@printf "%s" "------------------------------------------------------------"
 	@printf "%s\n" "-------------------"
-	@printf "Linking: $(TARGET) ... "
-	@cd $(OBJDIR) && $(AR) rcsv ../$(TARGETDIR)/$(TARGET) $(OBJS) > $*.lmsgs;\
+
+endif
+
+ifeq ($(TOPDIR)/Source/Common/Source/$(notdir $(CURDIR)),$(CURDIR))
+$(TARGETDIR):
+	@printf "Creating directory: $(TARGETDIR) ... "
+	@mkdir -p $(TARGETDIR)
+	@printf "[OK]\n"
+
+$(OBJSDIR):
+	@printf "Creating directory: $(OBJSDIR) ... "
+	@mkdir -p $(OBJSDIR)
+	@printf "[OK]\n"
+
+CPPFILES	:=	$(foreach dir,$(CURDIR),$(notdir $(wildcard $(dir)/*.cpp))) 
+
+#####################
+export VPATH	:= $(CURDIR)
+export OBJS = $(CPPFILES:.cpp=.o)
+HEADERS = $(wildcard *.hpp)
+#####################
+
+$(TARGET): $(TARGETDIR) $(OBJSDIR)
+	@mkdir -p $(TARGETDIR)
+	@mkdir -p $(OBJSDIR)
+	@printf "Compiling common object files for $(TARGET)\n"
+	@/usr/bin/time -f "%E" -o $(OBJSDIR)/compiletime \
+	$(MAKE) --no-print-directory -C $(OBJSDIR) \
+	-f $(TOPSRC)/Pandora/MakefileCommon TARGET=$(TARGET) OBJSDIR=$(OBJSDIR) \
+	LOCALINCDIR=$(CURDIR)/Headers ZEDINCDIR=$(ZEDINCDIR) \
+	COPYFILES=False NOLIB=True $(BUILD_TYPE)
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+	@printf "Compile Time: "
+	@cat $(OBJSDIR)/compiletime
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+
+endif
+
+else
+##### In the intermediate build directory #####################################
+ifneq ($(NOLIB), True)
+ifneq ($(SHARED), False)
+$(TARGET): $(OBJS)
+	@printf "\n\n%s" "------------------------- MESSAGES FROM THE COMPILER ---"
+	@printf "%s\n" "-----------------------"
+	@cat *.cmsgs
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+	@printf "Linking $(TARGET) ... "
+	@$(CPP) -m$(BITSIZE) -shared -Wl,-soname,$(ZEDTARGET).so.1 \
+	-o $(TARGETDIR)/$(TARGET) $(OBJS) > $*.lmsgs
+	@printf "[OK]\n"
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+else
+$(TARGET): $(OBJS)
+	@printf "\n\n%s" "------------------------- MESSAGES FROM THE COMPILER ---"
+	@printf "%s\n" "-----------------------"
+	@cat *.cmsgs
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+	@printf "Linking $(TARGET) ... "
+	@ar rcsv $(TARGETDIR)/$(TARGET) $(OBJS) > $*.lmsgs
+	@printf "[OK]\n"
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+endif
+%.o: %.cpp
+	@printf "Compiling: $< ... "
+	@$(CPP) -MMD -MP -MF $*.d $(CPPFLAGS) -I$(LOCALINCDIR) $(ZEDINCDIR) \
+	$(SYSIPATH) $< -o $@ 2> $*.cmsgs;\
 	RETVAL=$$?;\
 	if [[ $$RETVAL == 0 ]]; then\
 		printf "[OK]\n";\
 	else\
+		printf "\n\n%s" "----------------------------------- ERROR ---------";\
+		printf "%s\n" "----------------------------";\
+		cat $*.cmsgs;\
+		printf "%s" "-------------------------------------------------------";\
+		printf "%s\n\n" "------------------------";\
 		exit 1;\
 	fi
+-include *.d
+else
+$(TARGET): $(OBJS)
 
-%.o: $(SOURCEDIR)/%.cpp
-	-mkdir -p $(OBJDIR)
-	$(CPP) $(CPPFLAGS) -DZED_BUILD_$(ZED_BUILD) -DZED_PLATFORM_$(BUILD_PLATFORM) \
-	-I$(COMMONINCDIR) $(ZEDINCDIR) $< -o $(OBJDIR)/$@
+%.o: %.cpp
+	@printf "Compiling: $< ... "
+	@$(CPP) -MMD -MP -MF $*.d $(CPPFLAGS) -I$(LOCALINCDIR) $(ZEDINCDIR) \
+	$(SYSIPATH) $< -o $@ 2> $*.cmsgs;\
+	RETVAL=$$?;\
+	if [[ $$RETVAL == 0 ]]; then\
+		printf "[OK]\n";\
+	else\
+		printf "\n\n%s" "----------------------------------- ERROR ---------";\
+		printf "%s\n" "----------------------------";\
+		cat $*.cmsgs;\
+		printf "%s" "-------------------------------------------------------";\
+		printf "%s\n\n" "------------------------";\
+		exit 1;\
+	fi
+-include *.d
+endif
+#%.o: $(SOURCEDIR)/%.cpp
+#	-mkdir -p $(OBJDIR)
+#	$(CPP) $(CPPFLAGS) -DZED_BUILD_$(ZED_BUILD) -DZED_PLATFORM_$(BUILD_PLATFORM) \
+#	-I$(COMMONINCDIR) $(ZEDINCDIR) $< -o $(OBJDIR)/$@
 
-.PHONY: copy
+#.PHONY: copy
+#
+#copy:
+#	-mkdir -p $(ZEDPATH)/include/$(PLATFORM)
+#	-mkdir -p $(ZEDPATH)/lib/$(PLATFORM)
+#	if test -d ./Headers; then cp -f ./Headers/*.hpp $(ZEDPATH)/include/$(PLATFORM)/; fi
+#	cp -rf $(COMMONINCDIR)/* $(ZEDPATH)/include/$(PLATFORM)/
+#	cp -f $(TARGETDIR)/*.a $(ZEDPATH)/lib/$(PLATFORM)/
 
-copy:
-	-mkdir -p $(ZEDPATH)/include/$(PLATFORM)
-	-mkdir -p $(ZEDPATH)/lib/$(PLATFORM)
-	if test -d ./Headers; then cp -f ./Headers/*.hpp $(ZEDPATH)/include/$(PLATFORM)/; fi
-	cp -rf $(COMMONINCDIR)/* $(ZEDPATH)/include/$(PLATFORM)/
-	cp -f $(TARGETDIR)/*.a $(ZEDPATH)/lib/$(PLATFORM)/
-
-.PHONY: clean
-clean:
-	-rm -rf $(COMMONDIR)/Obj
-	-rm -rf $(COMMONDIR)/Lib
+#.PHONY: clean
+#clean:
+#	-rm -rf $(COMMONDIR)/Obj
+#	-rm -rf $(COMMONDIR)/Lib
 
 endif
+
+#####################
+ifeq ($(COPYFILES), True)
+.PHONY: copyfiles
+$(ZEDPATH)/include/$(PLATFORM):
+	@printf "Creating directory: $(ZEDPATH)/include/$(PLATFORM) ... "
+	@mkdir -p $(ZEDPATH)/include/$(PLATFORM)
+	@printf "[OK]\n"
+
+$(ZEDPATH)/lib/$(PLATFORM)/$(ARCH)/$(BITSIZE):
+	@printf "Creating directory: $(ZEDPATH)/lib/$(PLATFORM)/$(ARCH)/$(BITSIZE) ... "
+	@mkdir -p $(ZEDPATH)/lib/$(PLATFORM)/$(ARCH)/$(BITSIZE)
+	@printf "[OK]\n"
+
+copyfiles: $(ZEDPATH)/include/$(PLATFORM) $(ZEDPATH)/lib/$(PLATFORM)/$(ARCH)/$(BITSIZE)
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+	@printf "Copying local header files to: $(ZEDPATH)/include/$(PLATFORM) ..."
+	@printf " "
+	@if test -d ./Headers; then cp -f ./Headers/*.hpp \
+	$(ZEDPATH)/include/$(PLATFORM)/; fi
+	@printf "[OK]\n"
+	@printf "Copying common header files to: $(ZEDPATH)/include/$(PLATFORM) .."
+	@printf ". "
+	@cp -rf $(TOPSRC)/Common/Headers/* $(ZEDPATH)/include/$(PLATFORM)/
+	@printf "[OK]\n"
+	@printf "Copying library files to $(ZEDPATH)/lib/$(PLATFORM)/$(ARCH)/$(BITSIZE) ... "
+	@files=$$(ls $(TARGETDIR)/*.a 2> /dev/null | wc -l);\
+	if [ "$$files" != "0" ] ; then cp -f $(TARGETDIR)/*.a \
+	$(ZEDPATH)/lib/$(PLATFORM)/$(ARCH)/$(BITSIZE)/; fi
+	@files=$$(ls $(TARGETDIR)/*.so 2> /dev/null | wc -l);\
+	if [ "$$files" != "0" ] ; then cp -f $(TARGETDIR)/*.so \
+	$(ZEDPATH)/lib/$(PLATFORM)/$(ARCH)/$(BITSIZE)/; fi
+	@printf "[OK]\n"
+	@printf "%s" "------------------------------------------------------------"
+	@printf "%s\n" "-------------------"
+endif
+#####################
+
